### ISSUE TITLE
switch from free-mode to image-overlay: zoom is not preserved

### ISSUE THREAD

**Issue by fabfabBesnard** [romi/3d-plantviewer#120]
but zoom is preserved the other way around

**Comment by gregho67** [comment]
One of the app's developer confirmed that this bug cannot be fixed. The zoom in 2D and 3D works differently which means that the zoom applied to the 3D workspace cannot be transferred to the 2D plane. The 2D zoom however stays the same when switching between images, and it can be applied to the 3D plane by making a 3D zoom at the same time. This means that when zoom on an image, the same zoom is applied to the 3D workspace. From 2D to 3D this technique works but not the other way around.
