### ISSUE TITLE
Can't get Segmentation 2D Evaluation data from database

### ISSUE THREAD

**Issue by gregho67** [romi/3d-plantviewer#127]
In order to show the plant evaluation on the 3D explorer, you need to be able to get the data you need from the database. But the Segmentation 2D evaluation is not referenced in the files of the plant that are loaded in the database. That means that you can't access this data within the 3D explorer. The files of the virtual plant and/or the code for the `plantdb` module have to be updated in order to be able to get the plant evaluation data from the local database server. This means that a category **Evaluation** has to be visible on the local database (on `http://localhost:5000/scans/virtual_plant` for example).

**Comment by fabfabBesnard** [comment]
resolve by Nabil with a fix in plantdb
