### ISSUE TITLE
Mistake in the read me : build docker image

### ISSUE THREAD

**Issue by MarieTiss** [romi/3d-plantviewer#144]
The file `Dockerfile` is located in the subfolder named `docker`.

First you have to run a : 
`cd plant-3d-explorer/docker/`

And so you can run the command to build the docker image :
`docker build -t roboticsmicrofarms/plant-3d-explorer:2.1 .`

**Comment by EvanZarrella** [comment]
Fixed in https://github.com/romi/plant-3d-explorer/pull/156
