### ISSUE TITLE
The automated measures filter of the main menu page is broken ?

### ISSUE THREAD

**Issue by fabfabBesnard** [romi/3d-plantviewer#169]
Expected behavior: when *automated* measures are present, the button should turn blue.
Observed behavior: it is black even when automated measures are present in the dataset (for example, the phyllotaxis plots can display these measures present in the dataset

Reproducible test:
Database version=docker pull from evanzarrella/plantdb:experimental
Plant-3d-explorer: master branch
test database for the plant-3d-explorer

example: the 'automated' button stays black
![image](https://user-images.githubusercontent.com/20174786/176892089-12491b76-a3db-4ddf-ba00-9072b44fb1e5.png)

while after open, the dataset shows automated measurement in the plots (blue curve):
![image](https://user-images.githubusercontent.com/20174786/176892279-e4256f01-5785-42f7-97ab-893f1839ea41.png)

**Comment by EvanZarrella** [comment]
I think you meant automated measurements right ? 
Because AFAIK I don't see anything broken regarding manual measurements.
On the other hand, the button for Automated measures should effectively turn blue. 

I will investigate

**Comment by fabfabBesnard** [comment]
you're right: I messed up manual and automated in my description !
I edited the issue report: the problem is with automated button (not manual button)

**Comment by EvanZarrella** [comment]
I'll get on it on Monday

**Comment by EvanZarrella** [comment]
This was just a typo in ScanList with regard to p3dexp. The main fix is in the latest version of plantdb.
Just pull the usual `evanzarrella/plantdb:experimental`
