### ISSUE TITLE
BUG: Pcd color is always white when changed

### ISSUE THREAD

**Issue by fabfabBesnard** [romi/3d-plantviewer#19]
No matter the color chosen, the pcd layer is always white when a change is applied. Default color is ok and can be reset.

**Comment by Raphalex46** [comment]
I don't see this behavior in the `transparency` branch, is it fixed on this branch ? If it is, this issue can be closed.

**Comment by fabfabBesnard** [comment]
ok, this bug is no longer present in the` transparency` branch. 
I let you close the issue !
